NACTOOL_DIR = $(shell pwd)/nactool
FLOW_TEST_DIR = $(shell pwd)/flow_test
######################################################################
all:
	$(MAKE) -C $(NACTOOL_DIR)
	$(MAKE) -C $(FLOW_TEST_DIR)
clean:
	$(MAKE) -C $(NACTOOL_DIR) clean
	$(MAKE) -C $(FLOW_TEST_DIR) clean
